runtime: go113
env_variables:
  PROJECT_ID: "hnsdbc"
  DEFAULT_BUCKET: "hnsdbc.appspot.com"

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.70
  target_throughput_utilization: 0.70
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 5

inbound_services:
- warmup

main: ./main
handlers:
- url: /icon.png
  static_files: static/images/icon.png
  upload: static/images/icon.png
- url: /images
  static_dir: static/images
- url: /main.js
  static_files: static/main.js
  upload: static/main.js
- url: /index.html
  static_files: static/index.html
  upload: static/index.html
- url: /error.html
  static_files: static/error.html
  upload: static/error.html
- url: /.*
  script: auto
